### ISSUE TITLE
Does not seem to work on W10P 20H2 19042.928

### ISSUE THREAD

**Issue by 8HoLoN** [0x546F6D/pttb_-_Pin_To_TaskBar#1]
Hi, 

It doesn't seem to work on W10P 20H2 19042.928.

Any Idea ?

`pinTotaskbar\pttb.exe abc.lnk`

**Comment by 0x546F6D** [comment]
I am currently on W10P 2004 19041.928 and it still works fine on my machine:
![2021-05-03 12_39_13-Greenshot](https://user-images.githubusercontent.com/75736384/116863008-4f9ad980-ac0e-11eb-9c44-db8b46335308.png)

I'll check it out when I'm forced to update but in the meantime, you might want to try syspin.exe:
https://www.technosys.net/products/utils/pintotaskbar

**Comment by 8HoLoN** [comment]
Same behavior with the original syspin (does nothing and no error)
cmd: `syspin "C:\Windows\notepad.exe" "Pin to taskbar"`
* output:
```
Pin To Taskbar Utility v0.99.9
Technosys Corporation, Copyright(c) 1998-2020, www.technosys.net
Freeware
                                      Coded by Berk Ceyhun OZGEN

```
* exit:
```
echo %errorlevel%
0
```
* result : notepad is not pinned to taskbar

**Comment by 0x546F6D** [comment]
I installed 20H2 on a VM and indeed, Microsoft removed the "Pin to Taskbar" Verb from the context menu (right click menu) of .lnk shortcut files. However, it is still on the extended context menu of this file type (shift+right click).
The "Pin to Taskbar" verb is still available from the context menu of .exe files, which is why pttb still works with .exe files but not with .lnk files anymore.
I guess I can access the extended context menu verbs through [ShellFolderItem](https://docs.microsoft.com/en-us/windows/win32/shell/shellfolderitem-object) and the ExtendedProperty / InvokeVerbEx methods.
I'll have a look.
Thanks for letting me know about this change.

**Comment by 0x546F6D** [comment]
> 
> 
> Same behavior with the original syspin (does nothing and no error)
> cmd: `syspin "C:\Windows\notepad.exe" "Pin to taskbar"`
> 
>     * output:
> 
> 
> ```
> Pin To Taskbar Utility v0.99.9
> Technosys Corporation, Copyright(c) 1998-2020, www.technosys.net
> Freeware
>                                       Coded by Berk Ceyhun OZGEN
> ```
> 
>     * exit:
> 
> 
> ```
> echo %errorlevel%
> 0
> ```
> 
>     * result : notepad is not pinned to taskbar

Syspin doesnt pin even a .exe to the taskbar? Could you check if pttb works with .exe on your machine? it does work with .exe on my VM. Only .lnk shortcuts are not getting pinned.

**Comment by 8HoLoN** [comment]
`pttb.exe "C:\Windows\notepad.exe"`` does nothing

And concerning the context menu (simple reight click), I have the option "pin to task bar" for both .lnk and .exe.

**Comment by 0x546F6D** [comment]
Indeed, the shortcut "pin to taskbar" didn't appear on the context menu because I had directly copy-pasted it from shared folder, I didn't create it inside the VM.
So now, i really don't know what could be the problem as pttb is working fine on my side, as shown in the following screenshot:
![result](https://user-images.githubusercontent.com/75736384/116974430-ce534d80-acc6-11eb-802a-af00237a9a3b.png)

I uploaded a pttbDebug.exe that creates a log file, like displayed above, which might provide some info about why it fails on your machine. The error 0x3F0 doesn't seem to be an issue, I am getting it from time to time even though the .exe/.lnk gets pinned anyway.

**Comment by 0x546F6D** [comment]
Indeed, "Pin to taskbar" was not available in the context menu of the .lnk shortcut because I had copy-pasted it directly from the shared folder instead of creating it from inside the VM.
With that out of the way, I currently really don't know why it is not working in your system while it does properly pin both .exe and .lnk files in the VM I created yesterday, after downloading the lastest Win10 iso from microsoft website (19042.631) and running Windows Update on that fresh install (->19042.964, didn't try .928 though):
![result](https://user-images.githubusercontent.com/75736384/116987337-99032b80-acd7-11eb-9f65-03217eca0951.png)

I uploaded pttbDebug.exe, which creates a log file as displayed above, that "might" provide some information as to why pttb fails. Error code 0x3F0 does not seems to be an issue though, as the .exe/.lnk still gets pinned to the taskbar nonetheless.

**Comment by 0x546F6D** [comment]
Could you try the latest pttb.exe I just uploaded? This issue might have been due to a wrong string initialization in my part, which caused problems if the locale name for "Pin to tas&kbar" and "Unpin from tas&kbar" has a string length > to the English locale. For example, the French locale is "Épingler à la barre des tâches" if I remember well, and only the 1st 1/2 of the string would be used by pttb, which it of course wouldnt be able to find when compared to the list of available verbs.
If your windows locale is English though, then I need to dig deeper.

**Comment by 8HoLoN** [comment]
Nice, that's was effectively an location problem.

```
**** pttb Injected ****
 * Pin to TaskBar Verb     -->>   Épingler à la &barre des tâches
 * UnPin from TaskBar Verb -->>   Désépingler de la b&arre des tâches

*** Unpin Prog from taskbar if pinned then (Re-)Pin  ***

-->> UnPin if aready Pinned
- Verbs list:
  - &Ouvrir
  - Ou&vrir l'emplacement du fichier
  - 
  - Exécuter en tant qu                
  - Partager avec Skype
  - R&ésoudre les problèmes de compatibilité
  - É&pingler à l                   
  - 
  - 
  - Analyser avec Microsoft Defender...
  - WinMerge
  - Épingler à la &barre des tâches
  - Restaurer les versions précé&dentes
  - 
  - C&ouper
  - &Copier
  - Créer un racco&urci
  - &Supprimer
  - Reno&mmer
  - P&ropriétés

-->> Pin to TaskBar
- Verbs list:
  - &Ouvrir
  - Ou&vrir l'emplacement du fichier
  - 
  - Exécuter en tant qu                
  - Partager avec Skype
  - R&ésoudre les problèmes de compatibilité
  - É&pingler à l                   
  - 
  - 
  - Analyser avec Microsoft Defender...
  - WinMerge
  - Épingler à la &barre des tâches    <<-- VERB FOUND
- GetLastError() code before DoIt: 0x0
- GetLastError() code after DoIt: 0x0
```
And that works as expected now, thx!

I have others questions:
* do you think it you be possible to add unpin feature ?
* do you think it you be possible to order the pinned app among the already pinned apps ?

**Comment by 0x546F6D** [comment]
Merci de m'avoir informer de ce probleme, cela fait des annees que je n'ai ni touche a un clavier azerty, ni bosser sur un windows Francais. Mais pour resoudre mon "syndrome JCVD", je devrais peut etre me faire une MV avec un Windows Francais :)

Regarding your questions:

- I did not need the unpin feature so far but pttb is already conceived with the idea to automatically unpin & re-pin the .exe/.lnk that are already pinned. And for that, I went as far as directly unpinning the .lnk located in %AppData%\Roaming\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar instead of the ones passed to pttb, because windows has trouble unpinning .lnk which have been modified after being pinned. For this reason, all the groundwork is already done so it shouldn't be too much trouble.
- unfortunately, pin to taskbar always add the last pinned object to the last position. I did look into that at one point and checked the registry changes that happen after a "pin to taskbar" or "position move in the taskbar":
[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Taskband]
"FavoritesResolve"=hex: ...
"Favorites"=hex: ...
However, even though I did find some patterns with the unicode string arrangements in those 2 big binary values, i could not find a source that explained how to generate those value, and so did not pursue it further.
For this reason, the only way I can think off at the moment is to unpin then re-pin them in the order you want.

**Comment by 8HoLoN** [comment]
So you're also french ?
`I can think off at the moment is to unpin then re-pin them in the order you want` that what I also think.

So, I saw that pinned appears in 2 folders:
* ImplicitAppShortcuts
* TaskBar

So I need to check if delete those files unpinned the app.
Then parse the registry to find the current order of pinned app.
Then reconstructed the pinned app "layout"

**Comment by 0x546F6D** [comment]
> So you're also french ?

I'm one of those expats who ended up spending half of their life abroad but yeah: born, raised and educated in France until I experienced the Erasmus life :)

I uploaded a new version of pttb, which accept -u/-U as a 1st argument to override the default force re-pin behavior and to only unpin from taskbar:
- pttb Path\to\.exe\or\.lnk\to\PinToTaskbar
- pttb -u Path\to\.exe\or\.lnk\to\UnPinFromTaskBar

Can you give it a try a let me know if it works properly in your locale as well?

**Comment by 8HoLoN** [comment]
Very nice, it's all good. 
On my side I continue to parse the registry key and I achieve to found the pinned app block and size (so that way I know the total number of current pinned apps)
I also found that not all pinned apps is in `%appdata%\Microsoft\Internet Explorer\Quick Launch\User Pinned`  `TaskBar` and `ImplicitAppShortcuts` but only in registry. For example if you "windows parameter" and pin that window, it will only appears in registry (so registry approach is better than looking for file in `%appdata%\Microsoft\Internet Explorer\Quick Launch\User Pinned` )

**Comment by 0x546F6D** [comment]
Great, you can always let me know what you find out if you'd like it to be implemented into pttb.

Btw, I currently use [stahky](https://github.com/joedf/stahky), which allows me to have access to 40+ programs from the taskbar. After organizing my "category folders" in the taskbar, "pinning" a program to one of those categories is now as simple as copy-pasting a shortcut to the corresponding folder. I am a big fan of this little program but it does have a few shortcoming for my needs, so I might add some stahky-like features to pttb at one point if I find the time.

In the meantime, I'll close this issue but don't hesitate to open a new one if you'd like pttb to edit the "Taskband" key in the registry as well.

Bonne journee.
